### ISSUE TITLE
Documentation links broken for Quartz 1.8.6

### ISSUE THREAD

**Issue by tototututitidev** [quartz-scheduler/quartz-scheduler.org-site#110]
Hello,

All the links in the following pages do not work:
- https://www.quartz-scheduler.org/documentation/quartz-1.8.6/examples/
- https://www.quartz-scheduler.org/documentation/quartz-1.8.6/tutorials/

Could you fix it?

I know it's an old version but one of our tools still uses it.

Thanks

Regards

**Comment by jhouserizer** [comment]
Thanks for pointing it out.
