### ISSUE TITLE
Website documentation issues (page glitches)

### ISSUE THREAD

**Issue by jhouserizer** [quartz-scheduler/quartz-scheduler.org-site#18]
There is some HTML garbage appearing about the table on on three of these pages:

http://www.quartz-scheduler.org/documentation/quartz-2.2.x/examples/

http://www.quartz-scheduler.org/documentation/quartz-2.1.x/examples/

http://www.quartz-scheduler.org/documentation/quartz-2.x/examples/

**Comment by zemian** [comment]
This is now fixed as part of quartz-scheduler/quartz#360
