### ISSUE TITLE
Quartz 2.3.0 Documentation

### ISSUE THREAD

**Issue by NicoTexas** [quartz-scheduler/quartz-scheduler.org-site#23]
Is the documentation repository moved?

I can't find the documentation for
https://github.com/quartz-scheduler/quartz/releases/tag/quartz-2.3.0

Thanks

**Comment by breun** [comment]
I was wondering about this as well. Quartz 2.3.0 was released over 1.5 years ago (April 2017), but the documentation on http://www.quartz-scheduler.org/documentation/ is still for 2.2.x.

**Comment by zemian** [comment]
Hi, sorry for the long delay. We have updated our Quartz documentation and they are now part of the main source code. Hopefully this should not go out of sync as we release new version. https://github.com/quartz-scheduler/quartz/blob/master/docs/index.adoc

**Comment by breun** [comment]
@zemian Will the 2.3.x documentation also be available at http://www.quartz-scheduler.org/documentation/ ? Currently that page still shows the 'current' documentation to be for version 2.2.x.

**Comment by zemian** [comment]
Hi @breun Yes, there is a PR #32 that should update the site. Waiting for it to be merge.
