### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by cadilhac** [quartz-scheduler/quartz-scheduler.org-site#37]
This link disappeared:

http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

**Comment by zemian** [comment]
@cadilhac This should be fixed now. But the site is being build right now. Please check after a few moment. Also, please not this link is no longer valid. You should navigate from the Home again to see the proper links.

**Comment by zemian** [comment]
It's done now. Please the appropriate version from http://www.quartz-scheduler.org/documentation/

**Comment by cadilhac** [comment]
But where in the doc?

**Comment by zemian** [comment]
The link I gave shows the latest 2.2.x release is 2.2.2

So maybe you looking for this? http://www.quartz-scheduler.org/documentation/quartz-2.2.2/tutorials/crontrigger.html

**Comment by zemian** [comment]
Or if you are looking latest 2.3.x that will be http://www.quartz-scheduler.org/documentation/2.3.1-SNAPSHOT/tutorials/crontrigger.html
